apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment
  labels: 
    app: nginx
# Specification for deployment 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    # Specification for pods
    spec:
      containers: 
      - name: nginx
        image: nginx
        ports:
        - containerPort: 8080
